apiVersion: v1
kind: ServiceAccount
metadata:
  name: capability-access
  namespace: <capability-namespace>
  labels:
    eks.amazonaws.com/role-arn: arn:aws:iam::<account-id>:role/CapabilityAccessFromKubernetes
    eks.amazonaws.com/sts-regional-endpoints: "true"
